### ISSUE TITLE
TypeError: unhashable type: 'csr_matrix'

### ISSUE THREAD

**Issue by ziyuang** [brandonrobertz/SparseLSH#3]
Windows with Python 3.4.

Here are the messages when I run the test code:

    SparseLSH\tests> python regression_tests.py
    E
    ======================================================================
    ERROR: test_can_query_using_existing_row (__main__.IndexThenQueryTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "regression_tests.py", line 32, in test_can_query_using_existing_row
        points = lsh.query(X_sim, num_results=1)
      File "C:\Python34\Lib\site-packages\sparselsh-0.0.2-py3.4.egg\sparselsh\lsh.py
    ", line 269, in query
        candidates.update(members)
    TypeError: unhashable type: 'csr_matrix'
    
    ----------------------------------------------------------------------
    Ran 1 test in 0.031s
    
    FAILED (errors=1)
    
    SparseLSH\tests> python test_bruteforce_e2e.py
    Traceback (most recent call last):
      File "test_bruteforce_e2e.py", line 107, in <module>
        run_lsh( bits, dimensions, hashtables, s, d)
      File "test_bruteforce_e2e.py", line 85, in run_lsh
        similar_points = query_index( lsh, X_sim.getrow(0))
      File "test_bruteforce_e2e.py", line 78, in query_index
        similar = lsh.query(x, num_results=1)
      File "C:\Python34\Lib\site-packages\sparselsh-0.0.2-py3.4.egg\sparselsh\lsh.py
    ", line 269, in query
    TypeError: unhashable type: 'csr_matrix'

**Comment by brandonrobertz** [comment]
Looking into it now. This library hasn't been tested in Python 3x

**Comment by brandonrobertz** [comment]
That part of the code needs to be rewritten to not use sets in order for this to be python3 compat. CSR Matrices aren't hashable in py3 because they can change. I'm sure this won't be the only issue we run into when porting this to 3x. 

Another thing off the top of my head is the removal of berkeley DB from the core python library.

Any ideas here? I'm looking into why the 2.7 version of a csr_matrix is hashable (yet, it can change) and the 3x version is not.

**Comment by brandonrobertz** [comment]
I've dug in further. In python2.7, `csr_matrix` simply uses `object.__hash__` as its own hashing method. This returns the object's position in memory. In python3.4, this method is undefined. I can fix the error by simply making `csr_matrix.__hash__ = object.__hash__` before we build our matrices. But this still doesn't make the library work with python 3.4.

**Comment by brandonrobertz** [comment]
FYI: this is now fixed for python 3 as of version 1.1.0

**Comment by sanjitas** [comment]
I still have that error in python 3.6. Do I have to modify anything?

**Comment by sanjitas** [comment]
sorry i am just using something very different but having the same error!

**Comment by brandonrobertz** [comment]
Upgrade to the latest version. I've fixed the hashing errors in the latest version of SparseLSH.

**Comment by brandonrobertz** [comment]
If this isn't an issue with SparseLSH, please open an issue with whatever library you are using. I fixed the hash key issues in SparseLSH by using lists, not sets. Mutable data in python 3+ don't have a hashable type because it can't guarantee a unique mapping. You can either override `__hash__` with some key scheme that will ensure a unique mapping based on its data or use a non-hashing data structure.
